name: Create Trustline

on:
  workflow_dispatch: # Manuel çalıştırmak için

jobs:
  create-trustline:
    runs-on: ubuntu-latest

    steps:
    - name: Depoyu Klonla
      uses: actions/checkout@v4

    - name: Python Kur
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Bağımlılıkları Kur
      run: |
        pip install stellar-sdk

    - name: Trustline Aç
      env:
        DISTRIBUTION_SECRET_KEY: ${{ secrets.DISTRIBUTION_SECRET_KEY }}
        ISSUER_PUBLIC_KEY: ${{ secrets.ISSUER_PUBLIC_KEY }}
      run: python3 scripts/create_trustline.py
